language: node_js
node_js:
  - "9"
before_script:
  - npm run build
before_deploy:
  - git config --local user.name "William Wong"
  - git config --local user.email "compulim@hotmail.com"
  - npm run versionCommit
deploy:
  - provider: npm
    api_key:
      secure: "H83ubPGrgMjGTqDoudLiGOCK+t9vBVuTytQuB9Z11pUCSxr9dTquXiYnr7ue9s6DJR/n/TY6KfYMylP9dDOMRC9UnyXiiRaHTxR834tWZKu+P6f+B5ADlJ9D81UO2MplWUTnHyz3YTIun51LlROOPKkd0EuLidMeZiuw/RsmKj7yPV/jmExzQiJvInKLeU9/XcPAoAXiyEBFfRz2btKuuv3YhyW1PR8nQbmjc3SEEFyIEagsJHNtqE/7Y7Ra/Ap1b0oWg7yDzYKCLCUPhxkpEgvNexjbVK9fTWhhrZYGxqXYTH3Xvd14KKoopjd/XmObvNcrARRphoz5GOUgAILrb0pHL/ioyh2lAb4Pg3TNqWnz1c95bwVTU/o3xvnHx4iLmN5PKvB8c2C8L9aRH+Y9vY3TiU+6nSyJWngIJvofGkQOz3dNcuO+O7YjeiRxYYYvshk7WOxY7qMF4eip2Snd9YCjDM4cAHE9/TTxetj9UE/sF/fJNZ/cyiTZwicryOQDXA13b+WjlErtsIjXbn2LN0QiqRSOtrDsqu2p/debgizTmQGL/X80V8vOMtisy4xC5ihZUbWCO0ZVV+6djfe+i03BI/BvOkq1mtIsprFtfPijsRrPvMqbDK7w3WvK4W0FP8EoFAxJqzDqMu3F0Q8JwLXU9Sm8fVnlZ2e/bLJC4pQ="
    email: "compulim@hotmail.com"
    on:
      branch: master
    skip_cleanup: true
    tag: master
  - provider: npm
    api_key:
      secure: "H83ubPGrgMjGTqDoudLiGOCK+t9vBVuTytQuB9Z11pUCSxr9dTquXiYnr7ue9s6DJR/n/TY6KfYMylP9dDOMRC9UnyXiiRaHTxR834tWZKu+P6f+B5ADlJ9D81UO2MplWUTnHyz3YTIun51LlROOPKkd0EuLidMeZiuw/RsmKj7yPV/jmExzQiJvInKLeU9/XcPAoAXiyEBFfRz2btKuuv3YhyW1PR8nQbmjc3SEEFyIEagsJHNtqE/7Y7Ra/Ap1b0oWg7yDzYKCLCUPhxkpEgvNexjbVK9fTWhhrZYGxqXYTH3Xvd14KKoopjd/XmObvNcrARRphoz5GOUgAILrb0pHL/ioyh2lAb4Pg3TNqWnz1c95bwVTU/o3xvnHx4iLmN5PKvB8c2C8L9aRH+Y9vY3TiU+6nSyJWngIJvofGkQOz3dNcuO+O7YjeiRxYYYvshk7WOxY7qMF4eip2Snd9YCjDM4cAHE9/TTxetj9UE/sF/fJNZ/cyiTZwicryOQDXA13b+WjlErtsIjXbn2LN0QiqRSOtrDsqu2p/debgizTmQGL/X80V8vOMtisy4xC5ihZUbWCO0ZVV+6djfe+i03BI/BvOkq1mtIsprFtfPijsRrPvMqbDK7w3WvK4W0FP8EoFAxJqzDqMu3F0Q8JwLXU9Sm8fVnlZ2e/bLJC4pQ="
    email: "compulim@hotmail.com"
    on:
      tags: true
    skip_cleanup: true
  - provider: releases
    api_key:
      secure: "cJlUHL9x/04mPANekBtNec+PxX4QsMXosapnT+bpxPOZq3u5Wr13OkYvcCjWi3B6u5LVdaxDrqF6xHtotHtT96RCSzmh0r8ffOdLhuJ2dADjlKgMgYCasgXBOnPaWErcVgYUz6vbQ+wzqALx8cmB4cPMAuXOcQmOetfU951ntZIccn47Z6Ddd1lRDG6wxDk+qCGewcHgbs/ic8b0bSJEkBCMdtLbCEv6ODT882HQT3/Jd3HN5oL4E6s57hcsSI+wVLsHILmoCndC5elfHpNxYs2kRxEZXRjWmzIuqLiOueBCk4BXsV2bXWwZdlOD168b8im3+aGSV/XOvkXlivLC5YsyAaQX6SarTsPOPzwZHwKl7A+gdENr15dLLOt6yn8arFTqRLs+mK0aeqNzUK+BU1e+9MyqDh+lq6nI+J5SSUvlfN52ElvnKe1UFUPlUE5RkW9BOosAzpxmzwvpx/EGP6Dkt+8Iw6XhyV5y3ALXcGZhiGqDj7xjZ8sju5cbq82wkOFWOAFNg5oroDRfTVviu74ckQlEpsdoiVH7Igom8xg2ba67dIEt1wJT5HBs1cymmCLlOIBwCF9BCeLTJpBp8hDt0Xi0g42+KeppR78vJ0ObXL1vWGSOs9Wlbu6sbeC1eSEyVQ9vYXFtmW3qM6hnjRfuStttU95r3E8D39FPDYQ="
    on:
      tags: true
    skip_cleanup: true
